services:
  # Titanic API Service
  titanic-api:
    build: .
    container_name: titanic-api
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://signoz-otel-collector:4317
      - OTEL_SERVICE_NAME=titanic-api
      - OTEL_SERVICE_VERSION=1.0.0
      - OTEL_RESOURCE_ATTRIBUTES=service.name=titanic-api,service.version=1.0.0
    networks:
      - signoz-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# Use existing SigNoz network
networks:
  signoz-net:
    external: true
    name: signoz-net